// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Ct_yfikgtIRjvzmJYKjrESYwp8abIOc',
    appId: '1:964146861421:web:a4cd02823ce9c3d0d43664',
    messagingSenderId: '964146861421',
    projectId: 'apple-ecommerce0',
    authDomain: 'apple-ecommerce0.firebaseapp.com',
    storageBucket: 'apple-ecommerce0.appspot.com',
    measurementId: 'G-TDT48LY3DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNToC9lGVpw50s8xYKPgNe94IGtuj6Q8',
    appId: '1:964146861421:android:bcde32b3f1b30d96d43664',
    messagingSenderId: '964146861421',
    projectId: 'apple-ecommerce0',
    storageBucket: 'apple-ecommerce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK5ehbwdI-HA1jOj6Wdfw-wcsGTavHgo0',
    appId: '1:964146861421:ios:0b902b93ed376009d43664',
    messagingSenderId: '964146861421',
    projectId: 'apple-ecommerce0',
    storageBucket: 'apple-ecommerce0.appspot.com',
    iosBundleId: 'lk.ceylonedge.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK5ehbwdI-HA1jOj6Wdfw-wcsGTavHgo0',
    appId: '1:964146861421:ios:6326af32f15c3163d43664',
    messagingSenderId: '964146861421',
    projectId: 'apple-ecommerce0',
    storageBucket: 'apple-ecommerce0.appspot.com',
    iosBundleId: 'com.example.apple.RunnerTests',
  );
}
